export const FINDED_USERS = [
  {
    customerType: 'CLIENT',
    hasPassiveOffer: false,
    overallInfo: {
      id: '130701367649',
      shortName: 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "54"',
      fullName: 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "54"',
      inn: '5032371695',
      kpp: '503201001',
      ogrn: '1235000152210',
      isVip: false,
      organizationPhone: '+7(000)000-00-01',
      organizationMail: 'test@test.test',
    },
  },
];

export const PARTY = [
  {
    value: 'ООО "КОМПАНИЯ 654"',
    unrestricted_value: 'ООО "КОМПАНИЯ 654"',
    data: {
      kpp: '590501001',
      capital: null,
      invalid: null,
      management: {
        name: 'Батракова Валентина Борисовна',
        post: 'ДИРЕКТОР',
        disqualified: null,
      },
      founders: null,
      managers: null,
      predecessors: null,
      successors: null,
      branch_type: 'MAIN',
      branch_count: 0,
      source: null,
      qc: null,
      hid: '157232108',
      type: 'LEGAL',
      state: {
        status: 'ACTIVE',
        code: null,
        actuality_date: 1723680000000,
        registration_date: 1429574400000,
        liquidation_date: null,
      },
      opf: {
        type: '2014',
        code: '12300',
        full: 'Общество с ограниченной ответственностью',
        short: 'ООО',
      },
      name: {
        full_with_opf: 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КОМПАНИЯ 654"',
        short_with_opf: 'ООО "КОМПАНИЯ 654"',
        latin: null,
        full: 'КОМПАНИЯ 654',
        short: 'КОМПАНИЯ 654',
      },
      inn: '5905027840',
      ogrn: '1155958033725',
      okpo: '43049838',
      okato: '57401367000',
      oktmo: '57701000001',
      okogu: '4210014',
      okfs: '16',
      okved: '46.69',
      okveds: null,
      authorities: null,
      documents: null,
      licenses: null,
      finance: {
        tax_system: null,
        income: 317000.0,
        expense: 421000.0,
        revenue: 317000.0,
        debt: 261157.17,
        penalty: null,
        year: 2023,
      },
      address: {
        value: 'г Пермь, ул Космонавта Леонова, д 47, кв 56',
        unrestricted_value: '614088, Пермский край, г Пермь, Индустриальный р-н, ул Космонавта Леонова, д 47, кв 56',
        invalidity: null,
        data: {
          postal_code: '614088',
          country: 'Россия',
          country_iso_code: 'RU',
          federal_district: 'Приволжский',
          region_fias_id: '4f8b1a21-e4bb-422f-9087-d3cbf4bebc14',
          region_kladr_id: '5900000000000',
          region_iso_code: 'RU-PER',
          region_with_type: 'Пермский край',
          region_type: 'край',
          region_type_full: 'край',
          region: 'Пермский',
          area_fias_id: null,
          area_kladr_id: null,
          area_with_type: null,
          area_type: null,
          area_type_full: null,
          area: null,
          city_fias_id: 'a309e4ce-2f36-4106-b1ca-53e0f48a6d95',
          city_kladr_id: '5900000100000',
          city_with_type: 'г Пермь',
          city_type: 'г',
          city_type_full: 'город',
          city: 'Пермь',
          city_area: null,
          city_district_fias_id: null,
          city_district_kladr_id: null,
          city_district_with_type: 'Индустриальный р-н',
          city_district_type: 'р-н',
          city_district_type_full: 'район',
          city_district: 'Индустриальный',
          settlement_fias_id: null,
          settlement_kladr_id: null,
          settlement_with_type: null,
          settlement_type: null,
          settlement_type_full: null,
          settlement: null,
          street_fias_id: '2f1e0a00-bc9b-44ec-b93a-7606b0b66765',
          street_kladr_id: '59000001000063700',
          street_with_type: 'ул Космонавта Леонова',
          street_type: 'ул',
          street_type_full: 'улица',
          street: 'Космонавта Леонова',
          stead_fias_id: null,
          stead_cadnum: null,
          stead_type: null,
          stead_type_full: null,
          stead: null,
          house_fias_id: 'bc7facb5-84ba-43ce-b361-97743d1101cd',
          house_kladr_id: '5900000100006371002',
          house_cadnum: '59:01:4416016:59',
          house_flat_count: null,
          house_type: 'д',
          house_type_full: 'дом',
          house: '47',
          block_type: null,
          block_type_full: null,
          block: null,
          entrance: null,
          floor: null,
          flat_fias_id: null,
          flat_cadnum: null,
          flat_type: 'кв',
          flat_type_full: 'квартира',
          flat: '56',
          flat_area: '-1',
          square_meter_price: '-1',
          flat_price: null,
          room_fias_id: null,
          room_cadnum: null,
          room_type: null,
          room_type_full: null,
          room: null,
          postal_box: null,
          fias_id: 'bc7facb5-84ba-43ce-b361-97743d1101cd',
          fias_code: '59000001000000006371002',
          fias_level: '8',
          fias_actuality_state: '0',
          kladr_id: '5900000100006371002',
          geoname_id: '511196',
          capital_marker: '2',
          okato: '57401367000',
          oktmo: '57701000001',
          tax_office: '5948',
          tax_office_legal: '5948',
          timezone: 'UTC+5',
          geo_lat: '57.96523',
          geo_lon: '56.177958',
          beltway_hit: null,
          beltway_distance: null,
          metro: null,
          divisions: null,
          qc_geo: '0',
          qc_complete: '0',
          qc_house: '2',
          history_values: null,
          unparsed_parts: null,
          source: '614088, ПЕРМСКИЙ КРАЙ, Г. ПЕРМЬ, УЛ. КОСМОНАВТА ЛЕОНОВА, Д. 47, КВ. 56',
          qc: '0',
        },
      },
      phones: null,
      emails: null,
      ogrn_date: 1429574400000,
      okved_type: '2014',
      employee_count: 3,
    },
  },
  {
    value: 'ВОЙСКОВАЯ ЧАСТЬ 6549',
    unrestricted_value: 'ВОЙСКОВАЯ ЧАСТЬ 6549',
    data: {
      kpp: '773301001',
      capital: null,
      invalid: null,
      management: {
        name: 'Хугаев Руслан Серапиевич',
        post: 'КОМАНДИР ВОЙСКОВОЙ ЧАСТИ 6549',
        disqualified: null,
      },
      founders: null,
      managers: null,
      predecessors: null,
      successors: null,
      branch_type: 'MAIN',
      branch_count: 0,
      source: null,
      qc: null,
      hid: '159657374',
      type: 'LEGAL',
      state: {
        status: 'ACTIVE',
        code: null,
        actuality_date: 1637193600000,
        registration_date: 821664000000,
        liquidation_date: null,
      },
      opf: {
        type: '2014',
        code: '75104',
        full: 'Федеральное государственное казенное учреждение',
        short: 'ФГКУ',
      },
      name: {
        full_with_opf: 'ВОЙСКОВАЯ ЧАСТЬ 6549',
        short_with_opf: null,
        latin: null,
        full: 'ВОЙСКОВАЯ ЧАСТЬ 6549',
        short: null,
      },
      inn: '5001022052',
      ogrn: '1035000703616',
      okpo: '08609893',
      okato: '45283559000',
      oktmo: '45367000000',
      okogu: '1319818',
      okfs: '12',
      okved: '84.22',
      okveds: null,
      authorities: null,
      documents: null,
      licenses: null,
      finance: null,
      address: {
        value: 'г Москва, Пятницкое шоссе, д 32',
        unrestricted_value: '125310, г Москва, р-н Митино, Пятницкое шоссе, д 32',
        invalidity: null,
        data: {
          postal_code: '125310',
          country: 'Россия',
          country_iso_code: 'RU',
          federal_district: 'Центральный',
          region_fias_id: '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
          region_kladr_id: '7700000000000',
          region_iso_code: 'RU-MOW',
          region_with_type: 'г Москва',
          region_type: 'г',
          region_type_full: 'город',
          region: 'Москва',
          area_fias_id: null,
          area_kladr_id: null,
          area_with_type: null,
          area_type: null,
          area_type_full: null,
          area: null,
          city_fias_id: '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
          city_kladr_id: '7700000000000',
          city_with_type: 'г Москва',
          city_type: 'г',
          city_type_full: 'город',
          city: 'Москва',
          city_area: 'Северо-западный',
          city_district_fias_id: null,
          city_district_kladr_id: null,
          city_district_with_type: 'р-н Митино',
          city_district_type: 'р-н',
          city_district_type_full: 'район',
          city_district: 'Митино',
          settlement_fias_id: null,
          settlement_kladr_id: null,
          settlement_with_type: null,
          settlement_type: null,
          settlement_type_full: null,
          settlement: null,
          street_fias_id: '7965af7a-a58f-4cc0-b8b4-c399ab9f14b8',
          street_kladr_id: '77000000000242700',
          street_with_type: 'Пятницкое шоссе',
          street_type: 'ш',
          street_type_full: 'шоссе',
          street: 'Пятницкое',
          stead_fias_id: null,
          stead_cadnum: null,
          stead_type: null,
          stead_type_full: null,
          stead: null,
          house_fias_id: 'cd0bb898-39ae-4866-ad2e-e519080392af',
          house_kladr_id: '7700000000024270017',
          house_cadnum: '77:08:0002016:1134',
          house_flat_count: null,
          house_type: 'д',
          house_type_full: 'дом',
          house: '32',
          block_type: null,
          block_type_full: null,
          block: null,
          entrance: null,
          floor: null,
          flat_fias_id: null,
          flat_cadnum: null,
          flat_type: null,
          flat_type_full: null,
          flat: null,
          flat_area: '-1',
          square_meter_price: '-1',
          flat_price: null,
          room_fias_id: null,
          room_cadnum: null,
          room_type: null,
          room_type_full: null,
          room: null,
          postal_box: null,
          fias_id: 'cd0bb898-39ae-4866-ad2e-e519080392af',
          fias_code: '77000000000000024270017',
          fias_level: '8',
          fias_actuality_state: '0',
          kladr_id: '7700000000024270017',
          geoname_id: '524901',
          capital_marker: '0',
          okato: '45283559000',
          oktmo: '45367000',
          tax_office: '7733',
          tax_office_legal: '7733',
          timezone: 'UTC+3',
          geo_lat: '55.8523199',
          geo_lon: '37.3648593',
          beltway_hit: 'OUT_MKAD',
          beltway_distance: '2',
          metro: [
            {
              name: 'Митино',
              line: 'Арбатско-Покровская',
              distance: 0.7,
            },
            {
              name: 'Пятницкое шоссе',
              line: 'Арбатско-Покровская',
              distance: 0.7,
            },
            {
              name: 'Волоколамская',
              line: 'Арбатско-Покровская',
              distance: 2.2,
            },
          ],
          divisions: null,
          qc_geo: '0',
          qc_complete: '5',
          qc_house: '2',
          history_values: null,
          unparsed_parts: null,
          source: '125310, Г.МОСКВА, Ш. ПЯТНИЦКОЕ, Д.32',
          qc: '0',
        },
      },
      phones: null,
      emails: null,
      ogrn_date: 1045008000000,
      okved_type: '2014',
      employee_count: null,
    },
  },
  {
    value: 'ТСЖ "МАЛАЯ ЯМСКАЯ, 65/4"',
    unrestricted_value: 'ТСЖ "МАЛАЯ ЯМСКАЯ, 65/4"',
    data: {
      kpp: '526001001',
      capital: null,
      invalid: null,
      management: {
        name: 'Кудрин Александр Евгеньевич',
        post: 'ПРЕДСЕДАТЕЛЬ',
        disqualified: null,
      },
      founders: null,
      managers: null,
      predecessors: null,
      successors: null,
      branch_type: 'MAIN',
      branch_count: 0,
      source: null,
      qc: null,
      hid: '158279462',
      type: 'LEGAL',
      state: {
        status: 'ACTIVE',
        code: null,
        actuality_date: 1673481600000,
        registration_date: 1313020800000,
        liquidation_date: null,
      },
      opf: {
        type: '2014',
        code: '20716',
        full: 'Товарищество собственников жилья',
        short: 'ТСЖ',
      },
      name: {
        full_with_opf: 'ТОВАРИЩЕСТВО СОБСТВЕННИКОВ ЖИЛЬЯ "МАЛАЯ ЯМСКАЯ, 65/4"',
        short_with_opf: 'ТСЖ "МАЛАЯ ЯМСКАЯ, 65/4"',
        latin: null,
        full: 'ТСЖ МАЛАЯ ЯМСКАЯ, 65/4',
        short: 'ТСЖ МАЛАЯ ЯМСКАЯ, 65/4',
      },
      inn: '5260308999',
      ogrn: '1115260016838',
      okpo: '92396997',
      okato: '22401373000',
      oktmo: '22701000001',
      okogu: '4210014',
      okfs: '16',
      okved: '68.32.1',
      okveds: null,
      authorities: null,
      documents: null,
      licenses: null,
      finance: {
        tax_system: null,
        income: 0.0,
        expense: 0.0,
        revenue: null,
        debt: null,
        penalty: null,
        year: 2023,
      },
      address: {
        value: 'г Нижний Новгород, ул Малая Ямская, д 65/4, офис 52',
        unrestricted_value:
          '603000, Нижегородская обл, г Нижний Новгород, Нижегородский р-н, ул Малая Ямская, д 65/4, офис 52',
        invalidity: null,
        data: {
          postal_code: '603000',
          country: 'Россия',
          country_iso_code: 'RU',
          federal_district: 'Приволжский',
          region_fias_id: '88cd27e2-6a8a-4421-9718-719a28a0a088',
          region_kladr_id: '5200000000000',
          region_iso_code: 'RU-NIZ',
          region_with_type: 'Нижегородская обл',
          region_type: 'обл',
          region_type_full: 'область',
          region: 'Нижегородская',
          area_fias_id: null,
          area_kladr_id: null,
          area_with_type: null,
          area_type: null,
          area_type_full: null,
          area: null,
          city_fias_id: '555e7d61-d9a7-4ba6-9770-6caa8198c483',
          city_kladr_id: '5200000100000',
          city_with_type: 'г Нижний Новгород',
          city_type: 'г',
          city_type_full: 'город',
          city: 'Нижний Новгород',
          city_area: null,
          city_district_fias_id: null,
          city_district_kladr_id: null,
          city_district_with_type: 'Нижегородский р-н',
          city_district_type: 'р-н',
          city_district_type_full: 'район',
          city_district: 'Нижегородский',
          settlement_fias_id: null,
          settlement_kladr_id: null,
          settlement_with_type: null,
          settlement_type: null,
          settlement_type_full: null,
          settlement: null,
          street_fias_id: '1783d626-6dea-4acf-9e21-d53fc9653d5a',
          street_kladr_id: '52000001000062300',
          street_with_type: 'ул Малая Ямская',
          street_type: 'ул',
          street_type_full: 'улица',
          street: 'Малая Ямская',
          stead_fias_id: null,
          stead_cadnum: null,
          stead_type: null,
          stead_type_full: null,
          stead: null,
          house_fias_id: '2d26497f-219b-42aa-9d75-d689cd223147',
          house_kladr_id: '5200000100006230070',
          house_cadnum: '52:18:0060142:53',
          house_flat_count: null,
          house_type: 'д',
          house_type_full: 'дом',
          house: '65/4',
          block_type: null,
          block_type_full: null,
          block: null,
          entrance: null,
          floor: null,
          flat_fias_id: null,
          flat_cadnum: null,
          flat_type: 'офис',
          flat_type_full: 'офис',
          flat: '52',
          flat_area: '-1',
          square_meter_price: '-1',
          flat_price: null,
          room_fias_id: null,
          room_cadnum: null,
          room_type: null,
          room_type_full: null,
          room: null,
          postal_box: null,
          fias_id: '2d26497f-219b-42aa-9d75-d689cd223147',
          fias_code: '52000001000000006230070',
          fias_level: '8',
          fias_actuality_state: '0',
          kladr_id: '5200000100006230070',
          geoname_id: '520555',
          capital_marker: '2',
          okato: '22401373000',
          oktmo: '22701000001',
          tax_office: '5260',
          tax_office_legal: '5260',
          timezone: 'UTC+3',
          geo_lat: '56.3094282',
          geo_lon: '43.9796258',
          beltway_hit: null,
          beltway_distance: null,
          metro: [
            {
              name: 'Горьковская',
              line: 'Автозаводская',
              distance: 1.1,
            },
            {
              name: 'Московская',
              line: 'Автозаводская',
              distance: 2.5,
            },
            {
              name: 'Московская',
              line: 'Сормовско-Мещерская',
              distance: 2.5,
            },
          ],
          divisions: null,
          qc_geo: '0',
          qc_complete: '0',
          qc_house: '2',
          history_values: null,
          unparsed_parts: null,
          source: '603000, НИЖЕГОРОДСКАЯ ОБЛАСТЬ, Г. НИЖНИЙ НОВГОРОД, УЛ. МАЛАЯ ЯМСКАЯ, Д.65, К.4, 52',
          qc: '0',
        },
      },
      phones: null,
      emails: null,
      ogrn_date: 1313020800000,
      okved_type: '2014',
      employee_count: null,
    },
  },
  {
    value: 'ГБОУ ШКОЛА № 654 ИМЕНИ А.Д. ФРИДМАНА',
    unrestricted_value: 'ГБОУ ШКОЛА № 654 ИМЕНИ А.Д. ФРИДМАНА',
    data: {
      kpp: '772301001',
      capital: null,
      invalid: null,
      management: {
        name: 'Видякин Сергей Львович',
        post: 'ДИРЕКТОР',
        disqualified: null,
      },
      founders: null,
      managers: null,
      predecessors: null,
      successors: null,
      branch_type: 'MAIN',
      branch_count: 0,
      source: null,
      qc: null,
      hid: '156951214',
      type: 'LEGAL',
      state: {
        status: 'ACTIVE',
        code: null,
        actuality_date: 1615939200000,
        registration_date: 1362009600000,
        liquidation_date: null,
      },
      opf: {
        type: '2014',
        code: '75203',
        full: 'Государственное бюджетное учреждение субъекта Российской Федерации',
        short: 'ГБУ',
      },
      name: {
        full_with_opf:
          'ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ГОРОДА МОСКВЫ "ШКОЛА № 654 ИМЕНИ А.Д. ФРИДМАНА"',
        short_with_opf: 'ГБОУ ШКОЛА № 654 ИМЕНИ А.Д. ФРИДМАНА',
        latin: null,
        full: 'ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ГОРОДА МОСКВЫ ШКОЛА № 654 ИМЕНИ А.Д. ФРИДМАНА',
        short: 'ГБОУ ШКОЛА № 654 ИМЕНИ А.Д. ФРИДМАНА',
      },
      inn: '7723864492',
      ogrn: '1137746171936',
      okpo: '17160311',
      okato: '45290590000',
      oktmo: '45395000000',
      okogu: '2300223',
      okfs: '13',
      okved: '85.14',
      okveds: null,
      authorities: null,
      documents: null,
      licenses: null,
      finance: null,
      address: {
        value: 'г Москва, ул Юных Ленинцев, д 35 к 2',
        unrestricted_value: '109129, г Москва, р-н Текстильщики, ул Юных Ленинцев, д 35 к 2',
        invalidity: null,
        data: {
          postal_code: '109129',
          country: 'Россия',
          country_iso_code: 'RU',
          federal_district: 'Центральный',
          region_fias_id: '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
          region_kladr_id: '7700000000000',
          region_iso_code: 'RU-MOW',
          region_with_type: 'г Москва',
          region_type: 'г',
          region_type_full: 'город',
          region: 'Москва',
          area_fias_id: null,
          area_kladr_id: null,
          area_with_type: null,
          area_type: null,
          area_type_full: null,
          area: null,
          city_fias_id: '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
          city_kladr_id: '7700000000000',
          city_with_type: 'г Москва',
          city_type: 'г',
          city_type_full: 'город',
          city: 'Москва',
          city_area: 'Юго-восточный',
          city_district_fias_id: null,
          city_district_kladr_id: null,
          city_district_with_type: 'р-н Текстильщики',
          city_district_type: 'р-н',
          city_district_type_full: 'район',
          city_district: 'Текстильщики',
          settlement_fias_id: null,
          settlement_kladr_id: null,
          settlement_with_type: null,
          settlement_type: null,
          settlement_type_full: null,
          settlement: null,
          street_fias_id: 'b05ce965-3bb0-4495-87f4-5eed877d3382',
          street_kladr_id: '77000000000001000',
          street_with_type: 'ул Юных Ленинцев',
          street_type: 'ул',
          street_type_full: 'улица',
          street: 'Юных Ленинцев',
          stead_fias_id: null,
          stead_cadnum: null,
          stead_type: null,
          stead_type_full: null,
          stead: null,
          house_fias_id: '0b74d2f8-25ba-4cf7-95ca-da14db3e0d6b',
          house_kladr_id: '7700000000000100004',
          house_cadnum: '77:04:0004001:1120',
          house_flat_count: null,
          house_type: 'д',
          house_type_full: 'дом',
          house: '35',
          block_type: 'к',
          block_type_full: 'корпус',
          block: '2',
          entrance: null,
          floor: null,
          flat_fias_id: null,
          flat_cadnum: null,
          flat_type: null,
          flat_type_full: null,
          flat: null,
          flat_area: '-1',
          square_meter_price: '-1',
          flat_price: null,
          room_fias_id: null,
          room_cadnum: null,
          room_type: null,
          room_type_full: null,
          room: null,
          postal_box: null,
          fias_id: '0b74d2f8-25ba-4cf7-95ca-da14db3e0d6b',
          fias_code: '77000000000000000100004',
          fias_level: '8',
          fias_actuality_state: '0',
          kladr_id: '7700000000000100004',
          geoname_id: '524901',
          capital_marker: '0',
          okato: '45290590000',
          oktmo: '45395000',
          tax_office: '7723',
          tax_office_legal: '7723',
          timezone: 'UTC+3',
          geo_lat: '55.7007471',
          geo_lon: '37.7446132',
          beltway_hit: 'IN_MKAD',
          beltway_distance: null,
          metro: [
            {
              name: 'Печатники',
              line: 'Курско-Рижский',
              distance: 1.2,
            },
            {
              name: 'Текстильщики',
              line: 'Курско-Рижский',
              distance: 1.2,
            },
            {
              name: 'Текстильщики',
              line: 'Таганско-Краснопресненская',
              distance: 1.2,
            },
          ],
          divisions: null,
          qc_geo: '0',
          qc_complete: '5',
          qc_house: '2',
          history_values: null,
          unparsed_parts: null,
          source: '109129, Г.МОСКВА, УЛ. ЮНЫХ ЛЕНИНЦЕВ, Д. 35К2',
          qc: '0',
        },
      },
      phones: null,
      emails: null,
      ogrn_date: 1362009600000,
      okved_type: '2014',
      employee_count: null,
    },
  },
];
